services:
  dev:
    build: .
    image: ubuntu-zsh
    stdin_open: true
    tty: true
    volumes:
      - workspace:/workspace
      - zsh-config:/root
      - ./host:/shared/host

volumes:
  workspace:
  zsh-config:
